/var/spool/slurmd/job2262196/slurm_script: line 13: conda: command not found
[I 2024-10-18 18:41:15,373] A new study created in RDB with name: MPk_nwLH_params_200
[W 2024-10-18 18:41:16,558] Trial 0 failed with parameters: {'lr': 0.00020468384756391303, 'wd': 0.17881192797857803, 'h1': 15, 'dr': 0.028078469264310124} because of the following error: FileNotFoundError(2, 'No such file or directory').
Traceback (most recent call last):
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/main.py", line 54, in __call__
    train_loader = data.create_dataset('train', self.seed, f_Pk, f_Pk_norm,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/data.py", line 68, in create_dataset
    data_set = make_dataset(mode, seed, f_Pk, f_Pk_norm, f_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/data.py", line 13, in __init__
    Pk = np.log10(np.load(f_Pk))
                  ^^^^^^^^^^^^^
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'all_MPks_nwLH.npy'
[W 2024-10-18 18:41:16,559] Trial 0 failed with value None.
CUDA Available
Traceback (most recent call last):
  File "/home/vk9342/USRP2024/pytorch/main.py", line 148, in <module>
    study.optimize(objective, n_trials, n_jobs=n_jobs)
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 247, in _run_trial
    raise func_err
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/main.py", line 54, in __call__
    train_loader = data.create_dataset('train', self.seed, f_Pk, f_Pk_norm, 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/data.py", line 68, in create_dataset
    data_set = make_dataset(mode, seed, f_Pk, f_Pk_norm, f_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/data.py", line 13, in __init__
    Pk = np.log10(np.load(f_Pk))
                  ^^^^^^^^^^^^^
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'all_MPks_nwLH.npy'
